"""Resemblyzer-based speaker similarity check for cloned voices.

Compares a source wav (used for cloning) against a generated wav produced by
the cloned voice. Gate: cosine similarity ≥ 0.85 (loose; voice cloning
through mimi_encoder + speaker_proj + flow_lm_prefill introduces fp16 drift).

Usage:
    python tools/verify_clone.py --source INPUT.wav --generated OUTPUT.wav
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--source", type=Path, required=True,
                   help="Original voice reference wav (input to the cloner).")
    p.add_argument("--generated", type=Path, required=True,
                   help="Wav generated by the cloned voice.")
    p.add_argument("--gate", type=float, default=0.85,
                   help="Cosine similarity gate (default: 0.85).")
    args = p.parse_args()

    from resemblyzer import VoiceEncoder, preprocess_wav

    src_wav = preprocess_wav(args.source)
    gen_wav = preprocess_wav(args.generated)

    enc = VoiceEncoder()
    src_emb = enc.embed_utterance(src_wav)
    gen_emb = enc.embed_utterance(gen_wav)

    cos = float(np.dot(src_emb, gen_emb) / (np.linalg.norm(src_emb) * np.linalg.norm(gen_emb)))
    print(f"Speaker cosine similarity: {cos:.4f}")
    if cos >= args.gate:
        print(f"PASS: ≥ {args.gate}")
        return 0
    print(f"FAIL: < {args.gate}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
